name: Deploy
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build: 
    runs-on: self-hosted
    steps: 
      - run: cd /home/andrey.bao/cat-text-generation-webui 
      - run: git pull
      - run: docker-compose up --build -d
