name: Deploy 1
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build: 
    runs-on: self-hosted
    steps: 
      - run: cd /home/andrey.bao/cat-text-generation-webui && git pull && docker-compose up --build -d
      - run: echo "Deployed"
